"""create chw_module_assignment table with upazila geographical support

Revision ID: 0022
Revises: 0021
Create Date: 2026-06-11 10:24:14.696483

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chw_module_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('upazila', sa.String(length=100), nullable=True),
    sa.Column('assigned_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'tenant_id', name='uq_module_assignment_tenant'),
    sa.UniqueConstraint('module_id', 'user_id', name='uq_module_assignment_user'),
    sa.UniqueConstraint('module_id', 'upazila', name='uq_module_assignment_upazila')
    )
    op.create_index(op.f('ix_chw_module_assignment_tenant_id'), 'chw_module_assignment', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chw_module_assignment_user_id'), 'chw_module_assignment', ['user_id'], unique=False)
    op.create_index(op.f('ix_chw_module_assignment_upazila'), 'chw_module_assignment', ['upazila'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chw_module_assignment_upazila'), table_name='chw_module_assignment')
    op.drop_index(op.f('ix_chw_module_assignment_user_id'), table_name='chw_module_assignment')
    op.drop_index(op.f('ix_chw_module_assignment_tenant_id'), table_name='chw_module_assignment')
    op.drop_table('chw_module_assignment')
    # ### end Alembic commands ###
