"""Stage 2-draft (was Stage D) — locale-keyed card drafter, per candidate.

Per `docs/ARCHITECTURE_RESET.md`:

- Stage 2-draft takes one `module_candidate_draft`, drafts cards in the
  deployment primary locale, and persists a `module` row as
  `lifecycle_status='draft'` with `module_json.cards` populated.
- When a semantically similar **active** module exists (any non-retired row,
  latest version per family), an LLM merges the old and new card sets
  (new wins on conflict), retires the matched row, and writes a new draft
  version in the same `module_family`.
- Quiz, search metadata, embedding (chained), and gap-classification are
  separate post-publish Celery workers; this stage enqueues them via
  ``DraftPipeline.enqueue_post_publish`` once the module row has been committed.
  Per-card search metadata is generated before module-level search metadata.
- `module_card_validator` runs on each drafted card; cards with hard
  violations are dropped, soft warnings are annotated as `field_flags`.
- If the validator strips the module below `card_min_count`, the candidate
  is skipped.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from platform_service.config import get_settings
from platform_service.db.models.module import Module
from platform_service.db.models.module_candidate_draft import ModuleCandidateDraft
from platform_service.db.repositories.module_candidate_repository import (
    ModuleCandidateRepository,
)
from platform_service.db.repositories.module_drafter_repository import (
    ModuleDrafterRepository,
)
from platform_service.db.repositories.module_repository import ModuleRepository
from platform_service.services.card_drafter import CardDrafter
from platform_service.services.card_normalisation import card_row_to_dict
from platform_service.services.draft_pipeline import DraftPipeline
from platform_service.services.ingestion_cardinality import resolve_for_candidate
from platform_service.services.published_module_merger import (
    PublishedModuleMerger,
    PublishedModuleMergerError,
    published_module_to_merge_dict,
)
from platform_service.services.run_state_service import RunStateService

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class StageDResult:
    """Outcome of Stage 2-draft for one candidate."""

    candidate_id: UUID
    module_id: UUID | None
    cards_count: int
    # Quiz is generated by a separate post-publish worker; Stage 2-draft
    # always returns 0 here. The pipeline_orchestrator will enqueue the
    # quiz worker on a non-None module_id.
    questions_count: int
    insufficient_reason: str | None
    merged_from_module_id: UUID | None = None
    was_published_merge: bool = False


class StageDOrchestrator:
    def __init__(
        self,
        session: AsyncSession,
        *,
        card_drafter: CardDrafter | None = None,
        published_module_merger: PublishedModuleMerger | None = None,
        draft_pipeline: DraftPipeline | None = None,
        # Quiz / distractor-critique kwargs accepted for backwards-compat
        # with callers that still pass them; ignored here. Quiz generation
        # is now a post-publish Celery worker.
        quiz_drafter: object = None,
        distractor_critique: object = None,
    ) -> None:
        self._session = session
        self._candidate_repo = ModuleCandidateRepository(session)
        self._drafter_repo = ModuleDrafterRepository(session)
        self._module_repo = ModuleRepository(session)
        self._published_merger = published_module_merger or PublishedModuleMerger()
        self._pipeline = draft_pipeline or DraftPipeline(session, card_drafter=card_drafter)
        # Silence the unused-arg warnings without keeping references.
        del quiz_drafter, distractor_critique

    async def run(
        self,
        *,
        candidate_id: UUID,
        enqueue_post_publish: bool = True,
        skip_merge: bool = False,
        step_id: UUID | None = None,
    ) -> StageDResult:
        """Execute Stage 2-draft for one candidate.

        `enqueue_post_publish` controls whether quiz + embedding generation
        Celery tasks are fired after the module is persisted. Default True
        preserves the existing per-doc ingestion flow. The cross-source
        fusion runner passes False because it may DELETE a freshly-drafted
        module on cross-source coverage failure, which races with the
        post-publish workers and produces FK violations on insert. The
        runner re-enqueues after coverage validation passes.

        `skip_merge` when True skips merging new cards into similar
        active modules even when ``stage_d_published_merge_enabled`` is on
        (per-ingest opt-out from POST /admin/ingest).
        """
        candidate = await self._candidate_repo.get_candidate(candidate_id)
        if candidate is None:
            raise ValueError(f"module_candidate_draft {candidate_id} not found")

        candidate_dict = self._candidate_to_dict(candidate)
        cited_blocks, valid_block_ids = await self._pipeline.load_cited_blocks(candidate_dict)

        draft_outcome = await self._pipeline.draft_and_validate_cards(
            candidate_id=candidate_id,
            candidate_dict=candidate_dict,
            cited_blocks=cited_blocks,
            valid_block_ids=valid_block_ids,
        )
        if draft_outcome.insufficient_reason is not None:
            return StageDResult(
                candidate_id=candidate_id,
                module_id=None,
                cards_count=0,
                questions_count=0,
                insufficient_reason=draft_outcome.insufficient_reason,
            )
        cards = draft_outcome.cards or []

        source_document_ids = self._pipeline.extract_source_document_ids(candidate_dict)
        merged_from_id: UUID | None = None
        was_merge = False

        settings = get_settings()
        if settings.stage_d_published_merge_enabled and not skip_merge:
            if step_id is not None:
                run_state = RunStateService(self._session)
                await run_state.patch_step_input_summary(
                    step_id,
                    {
                        "activity": "published_module_merge",
                        "candidate_id": str(candidate_id),
                    },
                )
                await self._session.commit()
            merge_outcome = await self._try_published_merge(
                candidate_id=candidate_id,
                candidate=candidate,
                candidate_dict=candidate_dict,
                cards=cards,
                valid_block_ids=valid_block_ids,
            )
            if merge_outcome is not None:
                module, cards, merged_from_id, source_document_ids = merge_outcome
                was_merge = True
            else:
                module = None
        else:
            module = None

        if module is None:
            family = await self._drafter_repo.get_or_create_module_family(
                proposed_title=candidate_dict.get("proposed_title", "Untitled Module")
            )
            module = await self._drafter_repo.create_published_module(
                family=family,
                candidate=candidate_dict,
                cards=cards,
                source_document_ids=source_document_ids,
                quality_flags=candidate.quality_flags_jsonb,
            )

        await self._session.flush()
        module_id = module.id

        if enqueue_post_publish:
            await self._enqueue_post_publish(
                module_id,
                source_document_ids,
                ingestion_run_id=candidate.ingestion_run_id,
                candidate_id=candidate_id,
            )

        return StageDResult(
            candidate_id=candidate_id,
            module_id=module_id,
            cards_count=len(cards),
            questions_count=0,
            insufficient_reason=None,
            merged_from_module_id=merged_from_id,
            was_published_merge=was_merge,
        )

    async def _try_published_merge(
        self,
        *,
        candidate_id: UUID,
        candidate: ModuleCandidateDraft,
        candidate_dict: dict[str, Any],
        cards: list[dict[str, Any]],
        valid_block_ids: set[UUID],
    ) -> tuple[Module, list[dict[str, Any]], UUID, list[UUID]] | None:
        """Merge with an active (non-retired) module when the LLM finds a match.

        Returns ``(module, cards, superseded_id, source_document_ids)`` on
        success, or ``None`` to fall back to the standard create path.
        """
        active_rows = await self._module_repo.list_active_modules_for_merge()
        if not active_rows:
            return None

        active_ids = [row.id for row in active_rows]
        card_rows = await self._module_repo.list_cards_for_module_ids(active_ids)
        cards_by_module_id: dict[UUID, list[dict[str, Any]]] = {}
        for row in card_rows:
            if row.module_id is None:
                continue
            cards_by_module_id.setdefault(row.module_id, []).append(card_row_to_dict(row))

        existing_payloads = [
            published_module_to_merge_dict(m, cards_by_module_id.get(m.id, [])) for m in active_rows
        ]
        merge_block_ids = set(valid_block_ids)
        for payload in existing_payloads:
            merge_block_ids |= self._pipeline.block_ids_from_cards(payload.get("cards", []))

        cardinality = await resolve_for_candidate(candidate_dict, self._session)
        card_min, card_max = cardinality.card_bounds()

        try:
            merge_result = await self._published_merger.merge(
                candidate=candidate_dict,
                new_cards=cards,
                existing_modules=existing_payloads,
                valid_block_ids=merge_block_ids,
                card_min_count=card_min,
                card_max_count=card_max,
            )
        except PublishedModuleMergerError:
            logger.warning(
                "Stage 2-draft module merge failed for candidate %s; using standard create",
                candidate_id,
                exc_info=True,
            )
            return None

        if merge_result.matched_module_id is None:
            return None

        merged_cards = self._pipeline.validate_cards(
            merge_result.merged_cards,
            candidate_id=candidate_id,
        )
        if len(merged_cards) < card_min:
            logger.warning(
                "Stage 2-draft merge for candidate %s dropped below card_min_count; "
                "falling back to standard create (matched module not retired)",
                candidate_id,
            )
            return None

        matched = await self._session.get(Module, merge_result.matched_module_id)
        if matched is None or matched.lifecycle_status == "retired":
            logger.warning(
                "Stage 2-draft merge matched module %s is missing or retired",
                merge_result.matched_module_id,
            )
            return None

        source_ids: set[UUID] = set(self._pipeline.extract_source_document_ids(candidate_dict))
        for sid in matched.source_document_ids or []:
            source_ids.add(sid)
        source_document_ids = sorted(source_ids)

        quality_flags: dict[str, Any] | None = (
            dict(candidate.quality_flags_jsonb) if candidate.quality_flags_jsonb else None
        )
        if await self._module_repo.family_has_draft_other_than(matched.module_family_id):
            qf = dict(quality_flags or {})
            flags = list(qf.get("flags") or [])
            if "family_has_existing_draft" not in flags:
                flags.append("family_has_existing_draft")
            qf["flags"] = flags
            quality_flags = qf

        module = await self._drafter_repo.create_merged_draft_module(
            matched_published=matched,
            candidate=candidate_dict,
            cards=merged_cards,
            source_document_ids=source_document_ids,
            quality_flags=quality_flags,
            match_rationale=merge_result.match_rationale,
        )
        await self._module_repo.retire_module(matched.id)
        logger.info(
            "Stage 2-draft merged candidate %s into family %s (retired %s %s, new draft %s)",
            candidate_id,
            matched.module_family_id,
            matched.lifecycle_status,
            matched.id,
            module.id,
        )
        return module, merged_cards, matched.id, source_document_ids

    async def _enqueue_post_publish(
        self,
        module_id: UUID,
        source_document_ids: list[UUID],
        *,
        ingestion_run_id: UUID,
        candidate_id: UUID,
    ) -> None:
        await self._pipeline.enqueue_post_publish(
            module_id,
            source_document_ids,
            ingestion_run_id=ingestion_run_id,
            candidate_id=candidate_id,
        )

    @staticmethod
    def _candidate_to_dict(c: ModuleCandidateDraft) -> dict[str, Any]:
        return {
            "id": str(c.id),
            "ingestion_run_id": str(c.ingestion_run_id),
            "proposed_title": c.proposed_title,
            "scope_summary": c.scope_summary,
            "description_localized": c.description_localized,
            "domain": c.domain,
            "source_provenance": c.source_provenance_jsonb,
            "estimated_card_count": c.estimated_card_count,
            "estimated_quiz_count": c.estimated_quiz_count,
            "proposed_module_type": c.proposed_module_type,
            "previous_practice_summary": c.previous_practice_summary,
            "current_practice_summary": c.current_practice_summary,
            "rationale_summary": c.rationale_summary,
        }


__all__ = ["StageDOrchestrator", "StageDResult"]
