"""Stable prompt template identifiers and generation-type mapping."""

from __future__ import annotations

from mc_contracts.enums import GenerationType

MODULE_IDENTIFIER_TEMPLATE_ID = "module-identifier"
CROSS_SOURCE_FUSER_TEMPLATE_ID = "cross-source-fuser"
CARD_DRAFTER_TEMPLATE_ID = "card-drafter"
PUBLISHED_MODULE_MERGER_TEMPLATE_ID = "published-module-merger"
GAP_CLASSIFICATION_TEMPLATE_ID = "gap-classification"
ASSESSMENT_TOPIC_CLASSIFICATION_TEMPLATE_ID = "assessment-topic-classification"
SEARCH_METADATA_TEMPLATE_ID = "search-metadata"
CARD_SEARCH_METADATA_TEMPLATE_ID = "card-search-metadata"
CHAT_FAQ_TEMPLATE_ID = "chat-faq-synthesis"
CHAT_FEEDBACK_SUMMARY_TEMPLATE_ID = "chat-feedback-summary"
MODULE_DEMAND_TEMPLATE_ID = "module-demand-summary"
VISION_TEMPLATE_ID = "vision"
QUIZ_GENERATION_TEMPLATE_ID = "quiz-generation"
COACHING_RAG_TEMPLATE_ID = "coaching-rag"

PROMPT_REGISTRY: dict[str, GenerationType] = {
    MODULE_IDENTIFIER_TEMPLATE_ID: GenerationType.MODULE_IDENTIFICATION,
    CROSS_SOURCE_FUSER_TEMPLATE_ID: GenerationType.CROSS_SOURCE_FUSION,
    CARD_DRAFTER_TEMPLATE_ID: GenerationType.CARD_DRAFTING,
    PUBLISHED_MODULE_MERGER_TEMPLATE_ID: GenerationType.MODULE_PUBLISHED_MERGE,
    GAP_CLASSIFICATION_TEMPLATE_ID: GenerationType.MODULE_GAP_CLASSIFICATION,
    ASSESSMENT_TOPIC_CLASSIFICATION_TEMPLATE_ID: GenerationType.MODULE_ASSESSMENT_TOPIC_CLASSIFICATION,
    SEARCH_METADATA_TEMPLATE_ID: GenerationType.MODULE_SEARCH_METADATA,
    CARD_SEARCH_METADATA_TEMPLATE_ID: GenerationType.CARD_SEARCH_METADATA,
    CHAT_FAQ_TEMPLATE_ID: GenerationType.CHAT_FAQ_SYNTHESIS,
    CHAT_FEEDBACK_SUMMARY_TEMPLATE_ID: GenerationType.CHAT_FEEDBACK_SUMMARY,
    MODULE_DEMAND_TEMPLATE_ID: GenerationType.MODULE_DEMAND_SUMMARY,
    VISION_TEMPLATE_ID: GenerationType.VISION_EXTRACTION,
    QUIZ_GENERATION_TEMPLATE_ID: GenerationType.QUIZ_DRAFTING,
    COACHING_RAG_TEMPLATE_ID: GenerationType.COACHING_RAG,
}
