"""Module — a specific version of a logical module. Immutable once written.

Per `docs/ARCHITECTURE_RESET.md`:

- Cards live inline as a JSON array on `module_json`. There are no per-card
  rows and no card stable IDs.
- `embedding` is a per-module vector used for admin/web semantic search
  (and for the Android repo's runtime grounding fetch). Generated by the
  post-publish embedding worker; failure does not block the module.
- `visibility_window` is a nullable timestamp range; when set, the module
  surfaces in the "what's new" runtime flow. Reviewer/admin sets this when
  a content change (not a routine correction) is published.
- `clinically_reviewed` defaults false. Pipeline auto-publishes; admin
  flips this from the dashboard once a clinician has signed off.
- `lifecycle_status` is the simplified set `draft | published | retired`.
  Pipeline writes `published` directly (no `in_review` / `approved`
  intermediate; the W-6 reviewer queue was deleted).
- `module_type` enum: refresher | content_update | digital_proficiency.
- `urgent_publish` is a quality flag for the dashboard, not a publish gate.
"""

import uuid
from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import Boolean, DateTime, Float, Integer, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSTZRANGE, UUID
from sqlalchemy.orm import Mapped, mapped_column

from platform_service.config import get_settings
from platform_service.db.base import Base

_EMBEDDING_DIM = get_settings().embedding_dimension


class Module(Base):
    __tablename__ = "module"
    __table_args__ = (UniqueConstraint("module_family_id", "version", name="uq_module_family_version"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    module_family_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    title_localized: Mapped[dict[str, str]] = mapped_column(JSONB, nullable=False)
    description_localized: Mapped[dict[str, str] | None] = mapped_column(JSONB, nullable=True)

    domain: Mapped[str] = mapped_column(Text, nullable=False)
    sub_domain: Mapped[str | None] = mapped_column(Text, nullable=True)

    # refresher | content_update | digital_proficiency
    module_type: Mapped[str] = mapped_column(Text, nullable=False, default="refresher")
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    # Denormalised primary gap for quiz gap-state updates. Full mapping lives
    # in ``module_behavioural_gap`` (many gaps per module). Stage 2-draft
    # auto-creates one gap per module and links it as primary.
    primary_gap_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    estimated_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    # easy | moderate | hard
    difficulty_level: Mapped[str] = mapped_column(Text, nullable=False, default="moderate")
    source_document_ids: Mapped[list[uuid.UUID] | None] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=True
    )

    # MinIO path to module preview PNG. Defaults from the first linked
    # source_document thumbnail at creation; admins may override independently.
    thumbnail_storage_path: Mapped[str | None] = mapped_column(Text, nullable=True)

    urgent_publish: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # ── module content (cards inline; no per-card tables) ───────────
    # Shape: {"cards": [{"title": {"bn": ...}, "body": {"bn": ...}, ...}, ...]}.
    # Locale keys match deployment_primary_locale.
    module_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # Per-module embedding vector. The migration defines it as vector(N)
    # via pgvector; pgvector.sqlalchemy.Vector adapter handles the
    # client-side cast so a Python list[float] roundtrips cleanly to/from
    # the column. SQLAlchemy will bind None for unset (None) values.
    embedding: Mapped[list[float] | None] = mapped_column(Vector(_EMBEDDING_DIM), nullable=True)

    # When non-NULL, the module surfaces in the runtime "what's new" flow
    # for the duration. Admin sets/clears this from the dashboard.
    visibility_window: Mapped[Any | None] = mapped_column(TSTZRANGE, nullable=True)

    # Per-module pass threshold override (0.0–1.0). When NULL, the
    # module-completion worker falls back to settings.quiz_pass_threshold_default.
    pass_threshold_override: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Advisory quality flags carried forward from Stage 2's heuristic
    # (insufficient-source filter) and Stage 2-draft validator. Pipeline
    # writes these for the dashboard's "needs attention" filter; they are
    # NOT a publish gate. Shape: {"flags": ["insufficient_heading_coverage",
    # "thin_provenance"], "details": {...}}.
    # `none_as_null=True` so a Python None persists as SQL NULL (not the
    # JSONB literal `'null'`). The dashboard's `?has_quality_flags=` filter
    # uses `IS NULL` to distinguish "no flags set" from "explicit empty
    # flag set", so the storage representation has to match.
    quality_flags_jsonb: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB(none_as_null=True), nullable=True
    )

    # LLM-generated bilingual keywords, search phrases, and topic tags for
    # lexical retrieval (BM25 eval) and embedding enrichment. Written by the
    # post-publish search_metadata worker after card drafting.
    search_metadata_jsonb: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB(none_as_null=True), nullable=True
    )

    # ── post-publish quality flag ───────────────────────────────────────
    # Pipeline auto-publishes with clinically_reviewed=false. Admin flips
    # this from the dashboard once a clinician has read the module and
    # confirmed it is safe.
    clinically_reviewed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    clinically_reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    clinically_reviewed_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    # ── lifecycle ───────────────────────────────────────────────────────
    # draft | published | retired
    lifecycle_status: Mapped[str] = mapped_column(Text, nullable=False, default="draft")
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    # When this module-version was retired (admin action). Distinct from
    # `published_at` for the same row — a published module that is later
    # retired carries both timestamps.
    deprecated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    supersedes_module_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
